# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: election.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'election.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65lection.proto\"\xf0\x01\n\x0c\x45lectionData\x12\x10\n\x08regionID\x18\x01 \x01(\t\x12\x12\n\nregionName\x18\x02 \x01(\t\x12\x15\n\rregionAddress\x18\x03 \x01(\t\x12\x18\n\x10regionPostalCode\x18\x04 \x01(\t\x12\x14\n\x0c\x66\x65\x64\x65ralState\x18\x05 \x01(\t\x12\x11\n\toevpVotes\x18\x06 \x01(\x05\x12\x11\n\tspoeVotes\x18\x07 \x01(\x05\x12\x11\n\tfpoeVotes\x18\x08 \x01(\x05\x12\x13\n\x0bgrueneVotes\x18\t \x01(\x05\x12\x11\n\tneosVotes\x18\n \x01(\x05\x12\x12\n\ntimetstamp\x18\x0b \x01(\t\"3\n\x10\x45lectionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2M\n\x13\x45lectionDataService\x12\x36\n\x10sendElectionData\x12\r.ElectionData\x1a\x11.ElectionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'election_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECTIONDATA']._serialized_start=19
  _globals['_ELECTIONDATA']._serialized_end=259
  _globals['_ELECTIONRESPONSE']._serialized_start=261
  _globals['_ELECTIONRESPONSE']._serialized_end=312
  _globals['_ELECTIONDATASERVICE']._serialized_start=314
  _globals['_ELECTIONDATASERVICE']._serialized_end=391
# @@protoc_insertion_point(module_scope)
